level_five/level_five/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from userapp import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^userapp/', include('userapp.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^special/$', views.special, name='special')
]

level_five/userapp/urls.py
from django.conf.urls import url
from userapp import views

app_name= 'userapp'
urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^user_login/', views.user_login, name='user_login')
    ]

level_five/userapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
	user = models.OneToOneField(User)

	#additional
	portfolio_site = models.URLField(blank= True)
	profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

	def __str__(self):
		return self.user.username

level_five/userapp/forms.py
from django import forms
from django.contrib.auth.models import User
from userapp.models import UserProfileInfo

class UserForm (forms.ModelForm):
	password = forms.CharField(widget= forms.PasswordInput())

	class Meta():
		model = User
		fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
	class Meta():
		model = UserProfileInfo
		fields =('portfolio_site','profile_pic')

level_five/userapp/views.py
from django.shortcuts import render
from userapp.forms import UserProfileInfoForm,UserForm


from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
	return render(request,'userapp/index.html')


@login_required
def special(request):
	return HttpResponse("You are logged in, Nice!")


@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('index'))

def register(request):

	registered =False

	if request.method == "POST":
		user_form = UserForm(data= request.POST)
		profile_form =UserProfileInfoForm(data=request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			user.set_password(user.password)
			user.save()

			profile = profile_form.save(commit = False)
			profile.user= user

			if 'profile_pic' in request.FILES :
				profile.profile_pic = request.FILES['profile_pic']

			profile.save()

			registered = True
		else:
			print(user_form.errors,profile_form.errors)

	else:
		user_form= UserForm()
		profile_form = UserProfileInfoForm()

	return render(request,'userapp/registration.html',
							{'user_form': user_form,
							   'profile_form':profile_form,
							   'registered':registered})


def user_login(request):

    if request.method == 'POST':
       
        username = request.POST.get('username')
        password = request.POST.get('password')

     
        user = authenticate(username=username, password=password)

       
        if user:
           
            if user.is_active:
               
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        return render(request, 'userapp/login.html', {})

	

level_five/templates/userapp/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<nav>
	<div>
		<ul>
			<li><a href="{% url 'index' %}">HOME</a></li>
			<li><a href="{% url 'admin:index'%}">ADMIN</a></li>
			<li><a href="{% url 'userapp:register' %}">REGISTRATION</a></li>

			{%  if user.is_authenticated %}
			<li><a href="{% url 'logout' %}">Logout</a></li>
			{% else %}
			<li><a href="{% url 'userapp:user_login' %}">Login</a></li>
			{%  endif %}



		</ul>
	</div>
</nav>
<div>
{% block body_block %}
{% endblock %}
</div>
</body>
</html>

level_five/templates/userapp/index.html
{% extends "userapp/base.html" %}
{% block body_block %}

<div>
	<h1>This is home page of level five</h1>
</div>
{% endblock %}

level_five/templates/userapp/login.html
{% extends 'userapp/base.html' %}
{% block body_block %}

<div>
	<h1>Please login </h1>
	<form action="{% url 'userapp:user_login' %}" method="post">
		{% csrf_token %}
		<label for="username">Username:</label>
          <input type="text" name="username" placeholder="Enter Username">

          <label for="password">Password</label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">
		
	</form>

</div>

{% endblock %}

level_five/templates/userapp/registration.html
{% extends "userapp/base.html" %}
{% load staticfiles %}
{% block body_block %}

<div>
	{% if registered %}
	<h1>Thank you for registering!</h1>
	{% else %}
	<h1>Register Here!</h1>
	<h3>Fill out the form:</h3>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{user_form.as_p}}
		{{ profile_form.as_p }}
		<input type="submit" name="" value="Register">
	</form>
	{% endif %}
</div>
{% endblock %}